
# protobuf library
find_package(Protobuf QUIET)
if(Protobuf_FOUND)
    message("protobuf found : " ${Protobuf_INCLUDE_DIRS})

    if(${scnet_USE_PROTOBUF_LITE})
        get_filename_component(PB_LIB_NAME "${Protobuf_LITE_LIBRARIES}" NAME_WE)
        get_filename_component(PB_PARENT_DIR "${Protobuf_LITE_LIBRARIES}" DIRECTORY)
    else()
        get_filename_component(PB_LIB_NAME "${Protobuf_LIBRARIES}" NAME_WE)
        get_filename_component(PB_PARENT_DIR "${Protobuf_LIBRARIES}" DIRECTORY)
    endif()

    if(${scnet_BUILD_SHARED})
        if(WIN32)
            string(APPEND PB_LIB_NAME ".dll")
        elseif(APPLE)
            string(APPEND PB_LIB_NAME ".dylib")
        else()
            string(APPEND PB_LIB_NAME ".so")
        endif()

    else()
        if(WIN32)
            string(APPEND PB_LIB_NAME ".lib")
        else()
            string(APPEND PB_LIB_NAME ".a")
        endif()
    endif()
    string(APPEND PB_PARENT_DIR "/${PB_LIB_NAME}")
    message("Protobuf_LIBRARIES: " ${PB_PARENT_DIR})

    list(APPEND scnet_library_dependencies ${PB_PARENT_DIR})
    list(APPEND scnet_include_directories ${Protobuf_INCLUDE_DIRS})
else()
    message("Can not find protobuf. Using thirdparty dir.")

    if(WIN32)
        set(PB_LIB_NAME protobuf)
    else()
        set(PB_LIB_NAME libprotobuf)
    endif()

    if(${scnet_USE_PROTOBUF_LITE})
        string(APPEND PB_LIB_NAME "-lite")
    endif()

    if(${scnet_BUILD_SHARED})
        if(WIN32)
            string(APPEND PB_LIB_NAME ".dll")
        elseif(APPLE)
            string(APPEND PB_LIB_NAME ".dylib")
        else()
            string(APPEND PB_LIB_NAME ".so")
        endif()
    else()
        if(WIN32)
            string(APPEND PB_LIB_NAME ".lib")
        else()
            string(APPEND PB_LIB_NAME ".a")
        endif()
    endif()

    set(Protobuf_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/third-party/protobuf/src)
    message("Protobuf_INCLUDE_DIRS: " ${Protobuf_INCLUDE_DIRS})

    set(protobuf_BUILD_TESTS OFF CACHE BOOL "build test off")
    set(protobuf_WITH_ZLIB OFF CACHE BOOL "build zlib off")
    add_subdirectory(${PROJECT_SOURCE_DIR}/third-party/protobuf/cmake)
    list(APPEND scnet_library_dependencies libprotobuf)
    list(APPEND scnet_include_directories ${Protobuf_INCLUDE_DIRS})
endif()

# cppsocket library
set(cppsocket_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/third-party/cppsocket/source)
message("cppsocket_INCLUDE_DIRS: " ${cppsocket_INCLUDE_DIRS})

add_subdirectory(${PROJECT_SOURCE_DIR}/third-party/cppsocket)
list(APPEND scnet_library_dependencies cppsocket)
list(APPEND scnet_include_directories ${cppsocket_INCLUDE_DIRS})


message("scnet_library_dependencies: ${scnet_library_dependencies}")
message("scnet_include_directories: ${scnet_include_directories}")

if(WIN32)
	set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS TRUE)
    list(APPEND scnet_library_dependencies ws2_32)
else()
    list(APPEND scnet_library_dependencies pthread)
endif()
